services:
  db:
    image: postgres:13
    container_name: postgres_db_google
    environment:
      POSTGRES_DB: google
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - db
    networks:
      - backend
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/google
      - --username=admin
      - --password=admin
      - --defaultSchemaName=google_docs
      - update
    volumes:
      - ./migrations/changelog:/liquibase/changelog

  app:
    build:
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GITHUB_USER=${GITHUB_USER}
    container_name: google_module
    image: vuhtang/google-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db_google:5432/google
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8081
    networks:
      - backend
    ports:
      - "8081:8081"

volumes:
  postgres_data:

networks:
  backend: