-- liquibase formatted sql

-- changeset ivanvaryuhin:1742669455031-1
CREATE TABLE "actions_output_interface" ("action_id" BIGINT NOT NULL, "output_interface_id" BIGINT NOT NULL);

-- changeset ivanvaryuhin:1742669455031-2
CREATE TABLE "action_parameters_options" ("action_parameter_id" BIGINT NOT NULL, "options_id" BIGINT NOT NULL);

-- changeset ivanvaryuhin:1742669455031-3
CREATE TABLE "nested_field_options_nested" ("nested_field_option_id" BIGINT NOT NULL, "nested_id" BIGINT NOT NULL);

-- changeset ivanvaryuhin:1742669455031-4
CREATE TABLE "action_interfaces_spec" ("action_interface_id" BIGINT NOT NULL, "spec_id" BIGINT NOT NULL);

-- changeset ivanvaryuhin:1742669455031-5
CREATE TABLE "actions_input_parameters" ("action_id" BIGINT NOT NULL, "input_parameters_id" BIGINT NOT NULL);

-- changeset ivanvaryuhin:1742669455031-6
ALTER TABLE "actions_output_interface" ADD CONSTRAINT "uk23qxhx6a5o9s03hqi48f2o2kn" UNIQUE ("output_interface_id");

-- changeset ivanvaryuhin:1742669455031-7
ALTER TABLE "action_parameters_options" ADD CONSTRAINT "ukbppgskubh9itnuh27tc43510k" UNIQUE ("options_id");

-- changeset ivanvaryuhin:1742669455031-8
ALTER TABLE "nested_field_options_nested" ADD CONSTRAINT "ukea0ap8a63uvdsurbwr5g13l0d" UNIQUE ("nested_id");

-- changeset ivanvaryuhin:1742669455031-9
ALTER TABLE "action_interfaces_spec" ADD CONSTRAINT "ukmgqaw2fjr5fakdv879p8duurl" UNIQUE ("spec_id");

-- changeset ivanvaryuhin:1742669455031-10
ALTER TABLE "actions_input_parameters" ADD CONSTRAINT "ukn9fj4x8e5cadqwmuln5sel2c1" UNIQUE ("input_parameters_id");

-- changeset ivanvaryuhin:1742669455031-11
CREATE TABLE "action_interfaces" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "label" VARCHAR(255), "name" VARCHAR(255), "time" BOOLEAN, "type" VARCHAR(255), CONSTRAINT "action_interfaces_pkey" PRIMARY KEY ("id"));

-- changeset ivanvaryuhin:1742669455031-12
CREATE TABLE "action_parameters" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "help" VARCHAR(255), "label" VARCHAR(255), "name" VARCHAR(255), "required" BOOLEAN, "type" VARCHAR(255), "parent_action_parameter_id" BIGINT, CONSTRAINT "action_parameters_pkey" PRIMARY KEY ("id"));

-- changeset ivanvaryuhin:1742669455031-13
CREATE TABLE "actions" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "category" VARCHAR(255), "description" VARCHAR(255), "label" VARCHAR(255), "name" VARCHAR(255), CONSTRAINT "actions_pkey" PRIMARY KEY ("id"));

-- changeset ivanvaryuhin:1742669455031-14
CREATE TABLE "google_tokens" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "access_token" VARCHAR(2048), "id_token" VARCHAR(2048), "refresh_token" VARCHAR(2048), "scopes" VARCHAR(2048), "user_email" VARCHAR(255), CONSTRAINT "google_tokens_pkey" PRIMARY KEY ("id"));

-- changeset ivanvaryuhin:1742669455031-15
CREATE TABLE "nested_field_options" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "is_default_value" BOOLEAN, "label" VARCHAR(255), "type" VARCHAR(255), "value" VARCHAR(255), CONSTRAINT "nested_field_options_pkey" PRIMARY KEY ("id"));

-- changeset ivanvaryuhin:1742669455031-16
ALTER TABLE "actions_output_interface" ADD CONSTRAINT "fk5rx65gaw2st7fyg5cqxgxul8" FOREIGN KEY ("output_interface_id") REFERENCES "action_interfaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-17
ALTER TABLE "nested_field_options_nested" ADD CONSTRAINT "fk69ve9cuuoxknum9m6fxej9h0b" FOREIGN KEY ("nested_id") REFERENCES "action_parameters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-18
ALTER TABLE "action_interfaces_spec" ADD CONSTRAINT "fk83hhusyx5plmthfcgb5qov7yq" FOREIGN KEY ("action_interface_id") REFERENCES "action_interfaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-19
ALTER TABLE "actions_input_parameters" ADD CONSTRAINT "fk8w2ccrjra8pnpinsgco37dld6" FOREIGN KEY ("action_id") REFERENCES "actions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-20
ALTER TABLE "actions_input_parameters" ADD CONSTRAINT "fkhmin4schvyhsctuq686a20v2f" FOREIGN KEY ("input_parameters_id") REFERENCES "action_parameters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-21
ALTER TABLE "nested_field_options_nested" ADD CONSTRAINT "fkles1dgcfhtraulv8xcki3h2ea" FOREIGN KEY ("nested_field_option_id") REFERENCES "nested_field_options" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-22
ALTER TABLE "actions_output_interface" ADD CONSTRAINT "fknedlleoj994m7qrdkym0eu64g" FOREIGN KEY ("action_id") REFERENCES "actions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-23
ALTER TABLE "action_parameters_options" ADD CONSTRAINT "fkolgsgy7o7br5yygx3680vtkae" FOREIGN KEY ("action_parameter_id") REFERENCES "action_parameters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-24
ALTER TABLE "action_parameters" ADD CONSTRAINT "fksnee4xqdey5d0ah66ruxtcrru" FOREIGN KEY ("parent_action_parameter_id") REFERENCES "action_parameters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-25
ALTER TABLE "action_parameters_options" ADD CONSTRAINT "fkspthjpnby98oehr99rrkdbjqn" FOREIGN KEY ("options_id") REFERENCES "nested_field_options" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset ivanvaryuhin:1742669455031-26
ALTER TABLE "action_interfaces_spec" ADD CONSTRAINT "fksruxxffg57cysmiiyrhwmq57" FOREIGN KEY ("spec_id") REFERENCES "action_interfaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

