spring:
  application:
    name: google-docs
  datasource:
    url: jdbc:postgresql://localhost:5432/google
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: google_docs

google-docs:
  application:
    client-id: 66206194589-ba9umpocfl5jjmcb99abv7kpgspd7ede.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:5173
  module:
    uuid: 40fc9b0f-20f3-4dea-8e45-333eafe395a3
    name: googledocs
    label: Google Docs
    description: Google Docs integration module
    iconPath: mock/path
    isPublic: false
    theme: mockTheme

server:
  port: 8080
